apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  labels:
    name: voting-deployment
    app: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      name: voting-pod
      app: demo
  template:
    metadata:
      name: voting-pod
      labels:
        name: voting-pod
        app: demo
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80