apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo
spec:
  selector:
    name: result-pod
    app: demo
  ports:
  - port: 80
    targetPort: 80