apiVersion: v1
kind: Pod
metadata:
  name: voting-pod
  labels:
    app: demo
    type: voting
spec:
  containers:
    - name: voting-app
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80