apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo
spec:
  selector:
    name: voting-pod
    app: demo
  ports:
  - port: 80
    targetPort: 80